apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-xxacbbcx
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-xxacbbcx:9cd992ead753601421292cb2f8788533740b8c65@sha256:fe98cb69ba0c7df19679c2dffc2c8b61d0a494021117e5218c07e3cc7d5b4381
          name: container-image
